#!/usr/bin/env bash
# ==============================================================================
#  tools/build-singlefile.sh
#  Tao file don LilbowRecovery.bat tu cac script nguon.
#  Chay tren Ubuntu (hoac bat ky Linux/macOS).
#
#  Ket qua: dist/LilbowRecovery.bat (~700 KB)
#    - Nhung san ReimageTool.ps1, engine.ps1, boot.sdi (base64)
#    - Lan dau chay tren may Windows: tu tai boot.wim tu GitHub Releases
#    - Cac lan sau: chay hoan toan offline
#
#  Su dung:
#    chmod +x tools/build-singlefile.sh
#    ./tools/build-singlefile.sh [--release-tag v1.0.0]
# ==============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$SCRIPT_DIR/.."
DIST="$ROOT/dist"
OUT="$DIST/LilbowRecovery.bat"

GITHUB_REPO="nguyenngocanhhp82-arch/LilbowRecovery"
RELEASE_TAG="${1:-v1.0.0}"
# URL se dung khi tai boot.wim tu GitHub Releases
BOOT_WIM_URL="https://github.com/${GITHUB_REPO}/releases/download/${RELEASE_TAG}/boot.wim"
BOOT_SDI_URL="https://github.com/${GITHUB_REPO}/releases/download/${RELEASE_TAG}/boot.sdi"

echo "═══════════════════════════════════════════════════"
echo "  LilbowRecovery — Single-file builder"
echo "  Release tag : $RELEASE_TAG"
echo "  Output      : $OUT"
echo "═══════════════════════════════════════════════════"

# Kiem tra file nguon
MAIN_PS1="$ROOT/ReimageTool.ps1"
ENGINE_PS1="$ROOT/winpe/engine.ps1"
BOOT_SDI="$ROOT/winpe/dist/boot.sdi"

if [[ ! -f "$MAIN_PS1" ]]; then echo "[LOI] Khong tim thay: $MAIN_PS1" && exit 1; fi
if [[ ! -f "$ENGINE_PS1" ]]; then echo "[LOI] Khong tim thay: $ENGINE_PS1" && exit 1; fi

mkdir -p "$DIST"

# Encode base64 (Windows-compatible: no line wraps)
echo "[1/4] Encoding ReimageTool.ps1..."
B64_MAIN=$(base64 -w 0 "$MAIN_PS1")

echo "[2/4] Encoding engine.ps1..."
B64_ENGINE=$(base64 -w 0 "$ENGINE_PS1")

# boot.sdi la file rat nho (<1KB). Encode neu co, neu khong thi de trong.
B64_SDI=""
if [[ -f "$BOOT_SDI" ]]; then
    echo "[3/4] Encoding boot.sdi..."
    B64_SDI=$(base64 -w 0 "$BOOT_SDI")
else
    echo "[3/4] boot.sdi khong co — se tai tu GitHub Releases."
fi

echo "[4/4] Ghi $OUT..."

cat > "$OUT" << 'HEADER_END'
@echo off
setlocal EnableDelayedExpansion
:: ==============================================================================
::  LilbowRecovery — Single-file Launcher
::  Generated by tools/build-singlefile.sh
::  DO NOT EDIT — chỉnh sửa file nguồn rồi build lại.
:: ==============================================================================
:: Lan dau: tu giai nen script va tai boot.wim tu GitHub Releases (~500 MB).
:: Cac lan sau: chay hoan toan offline, khong can internet.
:: ==============================================================================

:: ── Leo quyen Administrator ───────────────────────────────────────────────────
net session >nul 2>&1
if errorlevel 1 (
    echo Dang yeu cau quyen Administrator...
    powershell -NoProfile -Command "Start-Process cmd -ArgumentList '/c \"\"%~f0\"\"' -Verb RunAs"
    exit /b
)

set "APPDIR=%ProgramData%\LilbowRecovery"
set "WINPE_WIM=%APPDIR%\sources\boot.wim"
set "WINPE_SDI=%APPDIR%\boot\boot.sdi"
set "MAIN_PS1=%APPDIR%\ReimageTool.ps1"
set "ENGINE_PS1=%APPDIR%\engine.ps1"

echo.
echo   ========================================
echo      LilbowRecovery -- Khoi dong...
echo   ========================================
echo.

:: ── Tao thu muc ──────────────────────────────────────────────────────────────
mkdir "%APPDIR%" 2>nul
mkdir "%APPDIR%\sources" 2>nul
mkdir "%APPDIR%\boot" 2>nul
mkdir "%APPDIR%\images" 2>nul
mkdir "%APPDIR%\logs" 2>nul

:: ── Giai nen ReimageTool.ps1 neu can ─────────────────────────────────────────
if exist "%MAIN_PS1%" goto :skip_main
echo [1/3] Giai nen ReimageTool.ps1...
powershell -NoProfile -Command ^
    "$data = (Get-Content -LiteralPath '%~f0' -Raw -Encoding UTF8);" ^
    "$m = [regex]::Match($data, '(?s)__MAIN_PS1_START__\r?\n(.+?)\r?\n__MAIN_PS1_END__');" ^
    "if(-not $m.Success){Write-Error 'Khong tim thay data MAIN_PS1';exit 1};" ^
    "[IO.File]::WriteAllBytes('%MAIN_PS1%', [Convert]::FromBase64String($m.Groups[1].Value.Trim()))"
if errorlevel 1 ( echo [LOI] Giai nen ReimageTool.ps1 that bai. && pause && exit /b 1 )
:skip_main

:: ── Giai nen engine.ps1 neu can ──────────────────────────────────────────────
if exist "%ENGINE_PS1%" goto :skip_engine
echo [2/3] Giai nen engine.ps1...
powershell -NoProfile -Command ^
    "$data = (Get-Content -LiteralPath '%~f0' -Raw -Encoding UTF8);" ^
    "$m = [regex]::Match($data, '(?s)__ENGINE_PS1_START__\r?\n(.+?)\r?\n__ENGINE_PS1_END__');" ^
    "if(-not $m.Success){Write-Error 'Khong tim thay data ENGINE_PS1';exit 1};" ^
    "[IO.File]::WriteAllBytes('%ENGINE_PS1%', [Convert]::FromBase64String($m.Groups[1].Value.Trim()))"
if errorlevel 1 ( echo [LOI] Giai nen engine.ps1 that bai. && pause && exit /b 1 )
:skip_engine

:: ── Giai nen / tai boot.sdi ──────────────────────────────────────────────────
if exist "%WINPE_SDI%" goto :skip_sdi
echo [3a/3] Giai nen boot.sdi...
powershell -NoProfile -Command ^
    "$data = (Get-Content -LiteralPath '%~f0' -Raw -Encoding UTF8);" ^
    "$m = [regex]::Match($data, '(?s)__BOOT_SDI_START__\r?\n(.+?)\r?\n__BOOT_SDI_END__');" ^
    "if($m.Success -and $m.Groups[1].Value.Trim() -ne 'EMPTY'){" ^
    "  [IO.File]::WriteAllBytes('%WINPE_SDI%', [Convert]::FromBase64String($m.Groups[1].Value.Trim()))" ^
    "} else {" ^
    "  $url = (Get-Content -LiteralPath '%~f0' -Raw) -replace '(?s).*__BOOT_SDI_URL__:' -replace '\r?\n.*';" ^
    "  Write-Host 'Tai boot.sdi tu:' $url.Trim();" ^
    "  Invoke-WebRequest -Uri $url.Trim() -OutFile '%WINPE_SDI%' -UseBasicParsing" ^
    "}"
if errorlevel 1 ( echo [LOI] boot.sdi that bai. && pause && exit /b 1 )
:skip_sdi

:: ── Tai boot.wim neu chua co (~500 MB, chi lan dau) ─────────────────────────
if exist "%WINPE_WIM%" goto :skip_wim
echo.
echo ============================================================
echo   QUAN TRONG: Can tai boot.wim (~500 MB) tu GitHub Releases.
echo   Vui long ket noi internet. Qua trinh nay chi xay ra 1 lan.
echo ============================================================
echo.

powershell -NoProfile -Command ^
    "$url = (Get-Content -LiteralPath '%~f0' -Raw) -replace '(?s).*__BOOT_WIM_URL__:' -replace '\r?\n.*';" ^
    "$url = $url.Trim();" ^
    "Write-Host 'URL:' $url;" ^
    "Write-Host 'Bat dau tai... (co the mat 5-20 phut tuy toc do mang)';" ^
    "try {" ^
    "  $wc = New-Object System.Net.WebClient;" ^
    "  $wc.DownloadProgressChanged += {Write-Progress -Activity 'Tai boot.wim' -PercentComplete $_.ProgressPercentage};" ^
    "  $wc.DownloadFileTaskAsync($url, '%WINPE_WIM%').GetAwaiter().GetResult();" ^
    "  Write-Host 'Tai xong!';" ^
    "} catch {" ^
    "  Write-Host 'Loi:' $_ -ForegroundColor Red;" ^
    "  Remove-Item '%WINPE_WIM%' -Force -ErrorAction SilentlyContinue;" ^
    "  exit 1" ^
    "}"
if errorlevel 1 (
    echo [LOI] Tai boot.wim that bai.
    echo Vui long kiem tra ket noi internet va thu lai.
    pause & exit /b 1
)
echo [OK] boot.wim tai xong.

:skip_wim

:: ── Chay ung dung chinh ───────────────────────────────────────────────────────
echo.
echo Dang khoi chay LilbowRecovery...
powershell -NoProfile -ExecutionPolicy Bypass -File "%MAIN_PS1%"
if errorlevel 1 (
    echo.
    echo Ung dung thoat voi loi. Xem log tai: %APPDIR%\logs\
    pause
)
endlocal
exit /b

HEADER_END

# Ghi URL markers
printf "\n__BOOT_WIM_URL__:%s\n" "$BOOT_WIM_URL" >> "$OUT"
printf "__BOOT_SDI_URL__:%s\n" "$BOOT_SDI_URL" >> "$OUT"

# Ghi embedded data
printf "\n__MAIN_PS1_START__\n%s\n__MAIN_PS1_END__\n" "$B64_MAIN" >> "$OUT"
printf "\n__ENGINE_PS1_START__\n%s\n__ENGINE_PS1_END__\n" "$B64_ENGINE" >> "$OUT"

if [[ -n "$B64_SDI" ]]; then
    printf "\n__BOOT_SDI_START__\n%s\n__BOOT_SDI_END__\n" "$B64_SDI" >> "$OUT"
else
    printf "\n__BOOT_SDI_START__\nEMPTY\n__BOOT_SDI_END__\n" >> "$OUT"
fi

# Stats
SIZE=$(du -sh "$OUT" | cut -f1)
echo ""
echo "═══════════════════════════════════════════════════"
echo "  HOAN TAT!"
echo "  File: $OUT"
echo "  Kich thuoc: $SIZE"
echo ""
echo "  Buoc tiep theo:"
echo "  1. Build boot.wim tren may Windows lab"
echo "     -> winpe/dist/boot.wim + boot.sdi"
echo "  2. Tao GitHub Release '$RELEASE_TAG' va upload:"
echo "     - winpe/dist/boot.wim"
echo "     - winpe/dist/boot.sdi"
echo "  3. Phan phoi file: dist/LilbowRecovery.bat"
echo "     Chi can 1 file nay cho nguoi dung cuoi!"
echo "═══════════════════════════════════════════════════"
