#!/usr/bin/env bash
# tools/push-to-github.sh
# Chay lan dau de push len GitHub.
# Can: GitHub Personal Access Token (PAT) hoac SSH key.

echo "═══════════════════════════════════════════════════"
echo "  Push LilbowRecovery len GitHub"
echo "═══════════════════════════════════════════════════"
echo ""
echo "1. Mo GitHub va tao repo (neu chua co):"
echo "   https://github.com/new"
echo "   - Name: LilbowRecovery"
echo "   - Visibility: Public"
echo "   - KHONG tick 'Add README'"
echo ""
echo "2. Tao Personal Access Token (PAT) neu chua co:"
echo "   https://github.com/settings/tokens/new"
echo "   - Note: LilbowRecovery"
echo "   - Expiration: 90 days"
echo "   - Tick: [x] repo (full control)"
echo "   - Nhan 'Generate token' va luu lai"
echo ""
echo "3. Push bang lenh sau (nhap PAT khi duoc hoi password):"
echo ""
echo "   cd \"$(dirname "$(realpath "$0")")/..\""
echo "   git push -u origin main"
echo ""
echo "   Username: nguyenngocanhhp82@gmail.com (hoac GitHub username)"
echo "   Password: [dan PAT vao day]"
echo ""
echo "4. Sau khi push xong, tao GitHub Release v1.0.0 va upload:"
echo "   https://github.com/nguyenngocanhhp82/LilbowRecovery/releases/new"
echo "   - Tag: v1.0.0"
echo "   - Title: LilbowRecovery v1.0.0"
echo "   - Upload 2 file:"
echo "       winpe/dist/boot.wim   (~500 MB)"  
echo "       winpe/dist/boot.sdi   (<1 KB)"
echo ""
echo "5. Build file don cuoi cung:"
echo "   bash tools/build-singlefile.sh v1.0.0"
echo "   -> dist/LilbowRecovery.bat (101 KB)"
echo ""
echo "6. Chia se file dist/LilbowRecovery.bat cho nguoi dung!"
echo "   Ho chi can copy 1 file nay va double-click."
echo "═══════════════════════════════════════════════════"
